In [53]:
import numpy as np
import pandas as pd
import sklearn 

Task 1

In [54]:
# Run this cell
# Do not modify this cell
from sklearn.datasets import load_iris
iris = load_iris()

data = iris['data']
feature_names = iris['feature_names']
target = iris['target']
target_names = iris['target_names']

print('First 5 rows:', data[:5], sep='\n', end='\n\n')
print('Feature names:', feature_names, sep='\n', end='\n\n')
print('Target indices:', target, sep='\n', end='\n\n')
print('Target names:', target_names, sep='\n')

First 5 rows:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Feature names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target indices:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

Target names:
['setosa' 'versicolor' 'virginica']


In [55]:
def get_data_frame(data, feature_names, target, target_names):
  df = pd.DataFrame(data, columns = feature_names)
  df['target name'] = target_names[target]
  return df


In [56]:
# Do not modify this cell
df = get_data_frame(data, feature_names, target, target_names)

assert isinstance(df, pd.DataFrame)
assert df.shape == (150, 5)
assert np.all(df.loc[[0, 75, 120], 'target name'].values == target_names)

Task 2


In [57]:
col = ["mean sepal length (cm)", "mean sepal width (cm)", "mean petal length (cm)", "mean petal width (cm)", "min sepal length (cm)", "min sepal width (cm)", "min petal length (cm)", "min petal width (cm)", "max sepal length (cm)", "max sepal width (cm)", "max petal length (cm)", "max petal width (cm)"]
def get_stats(df):
  mean = df.groupby(['target name']).mean()
  max = df.groupby(['target name']).max()
  min = df.groupby(['target name']).min()
  data = np.concatenate([mean, min, max], axis = 1)
  df_stats = pd.DataFrame( data,index = target_names, columns=col)
  return df_stats
get_stats(df)

mean sepal length (cm)  mean sepal width (cm)  \
setosa                       5.006                  3.428   
versicolor                   5.936                  2.770   
virginica                    6.588                  2.974   

            mean petal length (cm)  mean petal width (cm)  \
setosa                       1.462                  0.246   
versicolor                   4.260                  1.326   
virginica                    5.552                  2.026   

            min sepal length (cm)  min sepal width (cm)  \
setosa                        4.3                   2.3   
versicolor                    4.9                   2.0   
virginica                     4.9                   2.2   

            min petal length (cm)  min petal width (cm)  \
setosa                        1.0                   0.1   
versicolor                    3.0                   1.0   
virginica                     4.5                   1.4   

            max sepal length (cm)  max sepal width (cm)  \
setosa                        5.8                   4.4   
versicolor                    7.0                   3.4   
virginica                     7.9                   3.8   

            max petal length (cm)  max petal width (cm)  
setosa                        1.9                   0.6  
versicolor                    5.1                   1.8  
virginica                     6.9                   2.5

In [58]:
# Do not modify this cell
df_stats = get_stats(df)
assert df_stats.shape == (3, 12)
assert all(df_stats.index.to_list() == target_names)
assert np.allclose(df_stats.loc[:, "mean sepal length (cm)"].values,
            np.array([5.006, 5.936, 6.588]))
assert np.allclose(df_stats.loc[:, "min petal width (cm)"].values,
            np.array([0.1, 1.0, 1.4]))
assert np.allclose(df_stats.loc[:, "max petal length (cm)"].values,
            np.array([1.9, 5.1, 6.9]))

Task  3   

In [59]:
def remove_small_flowers(df, df_stats):
  a = df.loc[(df['sepal width (cm)'] > df_stats['mean sepal width (cm)'][0]) & (df['target name'] == df_stats.index[0]) , :]
  b = df.loc[(df['sepal width (cm)'] > df_stats['mean sepal width (cm)'][1]) & (df['target name'] == df_stats.index[1]) , :]
  c = df.loc[(df['sepal width (cm)'] > df_stats['mean sepal width (cm)'][2]) & (df['target name'] == df_stats.index[2]) , :]
  df = pd.concat([a, b, c], sort = True)
  #return df

#df = remove_small_flowers(df, df_stats)


In [61]:
# Do not modify this cell
assert remove_small_flowers(df, df_stats) is None
assert df.shape == (80, 5)
assert (df[['petal length (cm)']].min() == 1.0)[0]
assert (df[['petal length (cm)']].max() == 6.7)[0]

AssertionError: 

Task 4

In [62]:
# Do not modify this cell
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)
print(X.shape)

(506, 13)


/Users/macbookpro/Library/Python/3.8/lib/python/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Californi

In [63]:
col= ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']
def get_data_frame(X, y):
  df = pd.DataFrame(data = X, columns = col)
  df['MEDV'] = y
  return df

In [64]:
# Do not modify this cell
df = get_data_frame(X,y)

assert isinstance(df, pd.DataFrame)
assert df.shape == (506, 14)
assert df.columns.tolist()[:3] == ['CRIM','ZN','INDUS']
assert df.columns[-1] == 'MEDV'

Task 5

In [65]:
def three_less_expensive(df):
  df = df.sort_values('MEDV')
  return df.loc[df['CRIM'] > 0.5][:3]

In [66]:
# Do not modify this cell
top3 = three_less_expensive(df)
assert top3.MEDV.mean() == 5.2  
assert top3.INDUS.mean() == 18.1 
assert top3.TAX.mean() == 666.0 