In [ ]:
import numpy as np

Using libraries other than numpy is **prohibited**.

Բացի numpy-ից այլ գրադարանների օգտագործումն **արգելված է**։

**Error handling**

>1․ Եթե որպես ֆունկցիայի պարամետր ստանում եք numpy զանգված (վեկտոր կամ մատրից), և այն չի համապատասխանում խնդրում նշված չափին (dimensions) կամ չափերի անհամաձայնություններ կան, ապա վերադարցրեք(return) **"DimensionError"** տեքստը

>2․ Եթե որպես ֆունկցիայի պարամետր ստանում եք 2D numpy զանգված (մատրից), և այն հակադարձելի(invertable) չէ, հակառակ խնդրի պահանջի, ապա վերադարցրեք(return) **"NotInvertableError"** տեքստը

# Problems

Problem 1. Compute the euclidean distance between two arrays. 


> Հաշվիր 2 զանգվածների Էվկլիդյան հեռավորությունը։


```
a, b = np.array([1, 2]), np.array([1, 3])
print(dist(a, b))
>>1
```


In [ ]:
def dist(a, b):
  #Your code here

In [ ]:
# Do not modify this cell
a, b = np.array([1, 1]), np.array([1, 3])
assert dist(a, b) == 2

a, b = np.array([-10, 1.5]), np.array([0.9, 3.6])
assert round(dist(a, b), 2) == 11.1

a, b = np.array([1, 1, 1]), np.array([0, -1, 3])
assert dist(a, b) == 3

a, b = np.array([1, 0, -999]), np.array([1, 3])
assert dist(a, b) == "DimensionError"

a, b = np.array([10, -1, 9, 1, 2.98, -0.14]), np.array([0, -1, 3.14, np.pi, 99, np.e])
assert round(dist(a, b), 2) == 96.78

Problem 2. Normalize an array so the values range exactly between 0 and 1․

> Նորմավորիր զանգվածը այնպես, որ արժեքները լինեն 0-ից 1 միջակայքում։

```
a = np.array([1,2,3,4])
print(rescale(a))
>>[0, 0.3333333, 0.66666667, 1]
```



In [ ]:
def rescale(a):
  #Your code here

In [ ]:
# Do not modify this cell
assert np.all(rescale(np.array([1, 2, 3, 4])) == [0, 1/3, 2/3, 1])
assert np.all(rescale(np.array([0, 1])) == [0, 1])
assert np.all(rescale(np.array([0, 10])) == [0, 1])
assert np.all(rescale(np.array([1, 2, 4])) == [0, 1/3, 1])

Problem 3. Find the position of missing values in 1D numpy array.

> Գտիր բացակայող արժեքների տեղերը 1D numpy զանգվածում:


```
a = np.array([np.nan, 1, 2])
print(find(a))
>>[0]
```



In [ ]:
# a = (0, 3)
# return list(a)

In [ ]:
def find(a):
  #Your code here 
  

In [ ]:
# Do not modify this cell
assert np.all(find(np.array([np.nan, 1, 2, np.nan])) == [0, 3])
assert np.all(find(np.array([np.nan, np.nan])) == [0, 1])
assert np.all(find(np.array([np.e, 1, 2, 99])) == [])
assert np.all(find(np.array([np.e])) == [])
assert np.all(find(np.array([])) == [])

Problem 4. Given a numpy array 'a' that contains n elements, denote by b the set of its unique values ​​in ascending order, denote by m the size of array b. You need to create a numpy array with dimensions $n \times m$, in each row of which there must be a value of 1 in case it is equal to the value of the given index of array b, in other places it must be 0.

> Տրված է numpy զանգված 'a', որը պարունակում է n էլեմենտ, b-ով նշանակենք նրա ունիկալ արժեքների (արժեքներն առանց կրկնության) զանգվածը ըստ աճման կարգի, m-ով նշանակենք b զանգվածի չափը: Հարկավոր է ստեղծել numpy զանգված $n \times m$ չափերով, որի i-րդ տողի j-րդ սյան տեղում պետք է գրված լինի 1 այն դեպքում, երբ a-ի i-րդ անդամը հավասար է b֊ի j-րդ արժեքին, իսկ մնացած տեղերում պետք է լինեն 0֊ներ։


```
a = np.array([1, 1, 2, 3, 2, 4])
# b = np.array([1, 2, 3, 4])
print(convert(a))
>>[[1, 0, 0, 0],
  [1, 0, 0, 0],
  [0, 1, 0, 0],
  [0, 0, 1, 0],
  [0, 1, 0, 0],
  [0, 0, 0, 1]]
```



In [ ]:
def convert(a):
  #Your code here

In [ ]:
# Do not modify this cell
assert np.all(convert(np.array([0, 0, 2, 3, 2, 4])) ==
              [[1, 0, 0, 0],
               [1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 1, 0, 0],
               [0, 0, 0, 1]])

assert np.all(convert(np.array([-np.pi, 9])) ==
              [[1, 0],
               [0, 1]])

assert np.all(convert(np.array([-1, 1, 9, 10])) ==
              [[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])

assert np.all(convert(np.array([np.sqrt(2), np.sqrt(2), np.sqrt(2)])) ==
              [[1],
               [1],
               [1]])

Problem 5. Given a 2D numpy array 'a' of sizes $n \times m$. You need to pad the matrix with 0s so that the dimensions of the matrix become  $(n+2n_1) \times (m+2m_1)$
>Տրված է 2D numpy զանգված 'a' $n \times m$ չափերի, Հարկավոր է կողքերից հավասարաչափ 0-ներ ավելացնել այնպես, որ զանգվածի չափերը դառնան $(n+2n_1) \times (m+2m_1)$

```
a = np.array([[1, 1], [1, 1]])
n1 = 1
m1 = 2
print(padding(a, n1, m1))
>>[[0, 0, 0, 0, 0, 0], 
  [0, 0, 1, 1, 0, 0],
  [0, 0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0, 0]]
```



In [ ]:
def padding(a, n1, m1):
  #your code here

In [ ]:
# Do not modify this cell
assert np.all(padding(np.array([[1, 1], [1, 1]]), 1, 2) ==
              [[0, 0, 0, 0, 0, 0],
               [0, 0, 1, 1, 0, 0],
               [0, 0, 1, 1, 0, 0],
               [0, 0, 0, 0, 0, 0]])

assert np.all(padding(np.array([[1, 2], [1, 1]]), 0, 2) ==
              [[0, 0, 1, 2, 0, 0],
               [0, 0, 1, 1, 0, 0]])

assert np.all(padding(np.array([[9]]), 2, 2) ==
              [[0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 9, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

Problem 6. Given a 2D numpy array 'a' of sizes $n \times m$ and a 1D numpy array 'b' of size m. You need to find the distance(Euclidean) of the 'b' vector from the rows of the 'a' matrix. Fill the results in the numpy array.
Extra points for writing without a loop.
>Տրված է 2D numpy զանգված 'a' $n \times m$ չափերի և m չափանի 1D numpy զանգված 'b' անունով։ Հարկավոր է գտնել 'b' վեկտորի Էվկլիդյան հեռավորությունը 'a' մատրիցի տողերից և արդյունքները լցնել numpy զանգվածի մեջ։ Խնդիրը Broadcasting֊ի միջոցով լուծողները կստանան լրացուցիչ միավոր։

```
a = np.array([[1, 1],
              [0, 1],
              [1, 3],
              [4, 5]])
b = np.array([1, 1])
print(dist(a, b))
>>[0,1,2,5]
```



In [1]:
def dist(a, b):
  #your code here

In [ ]:
# Do not modify this cell
a, b = np.array([[1, 1],
                 [0, 1],
                 [1, 3],
                 [4, 5]]), np.array([1, 1])
assert np.all(dist(a, b) == [0., 1., 2., 5.])

a, b = np.array([[np.e, 0, 1.5],
                 [0, 1, -10]]), np.array([1, 3.14, 0])
assert np.all(np.round(dist(a, b)) == [4, 10])

a, b = np.array([[1, 1],
                 [0, 1]]), np.array([1, 1, 1])
assert dist(a, b) == "DimensionError"

Problem 7. Given a 2D numpy array 'a' of sizes $m \times n$ whose each line is labeled with 0 or 1 numbers and a  vector  (of size n) which is not labeled. You need to find the appropriate label for 'b'. In the 'a' matrix, find the line closest to 'b' (according to the Euclidean distance) and label 'b' with the label of that line.
>Տրված է $m \times n$ չափանի 2D numpy զանգված՝ 'a', որի յուրաքանչյուր տող պիտակավորված (label) է 0 կամ 1 թվերով և 'b' վեկտոր (n չափի) որը պիտակավորված չէ։ Հարկավոր է գտնել 'b'֊ի համապատասխան պիտակը (label)՝ գտնելով 'a' մատրիցում 'b'ին ամենամոտ  տողը (ըստ Էվկլիդյան հեռավորության) և 'b'֊ն պիտակավորեք այդ տողի պիտակով։

```
a = np.array([[1, -2],
              [2, 5],
              [-3, -10],
              [3, 2],
              [3, 2],
              [0, 1]])
labels = np.array([0,1,0,1,1,0])
b = np.array([10,10])
print(predict_label(a,labels,b))
>>1
```



In [ ]:
def predict_label(a,labels,b):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[1, -2],
              [2, 5],
              [-3, -10],
              [3, 2],
              [3, 2],
              [0, 1]])
labels = np.array([0, 1, 0, 1, 1, 0])

assert predict_label(a, labels, np.array([10, 10])) == 1
assert predict_label(a, labels, np.array([10, -10])) == 0
assert predict_label(a, labels, np.array([10, -1])) == 1
assert predict_label(a, labels, np.array([1, 1, 0])) == "DimensionError"

a = np.array([[0, 1, -2],
              [2, 1, 5],
              [-3, 3.5, -10],
              [3, 2, 9],
              [3, -2, 9]])
labels = np.array([0, 1, 0, 1, 1])
assert predict_label(a, labels, np.array([1])) == "DimensionError"
assert predict_label(a, labels, np.array([1, 1, 0])) == 0
assert predict_label(a, labels, np.array([1, 1, 10])) == 1

Problem 8. Given a 2D numpy array 'a' of sizes $m \times n$ with missing elements (NAN) and a string 'mode' $\in$ {"mean","min","max"}. You need to write the {"mean","min","max"} ('mode') of the corresponding column instead of the missing elements.
>Տրված է 2D numpy զանգված 'a' $m \times n$ չափերի, որն ունի բացակայող էլեմենտներ (NAN) ու տեքստային փոփոխական 'mode' $\in$ {"mean","min","max"}։ Հարկավոր է 'a' մատրիցի բացակայող էլեմենտների փոխարեն գրել համապատասխան սյան {միջինը, մինիմումը, մաքսիմումը} ըստ 'mode' փոփոխականի։

```
a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])
mode = "mean"
print(fill(a, mode))
>>[[  0.75 200.    10.  ]
 [  2.   110.    10.  ]
 [  0.   120.    11.  ]
 [  0.   400.    10.  ]
 [  1.   207.5    9.  ]]
```



In [ ]:
def fill(a, mode):
  #your code here

In [ ]:
# Do not modify this cell
a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])

assert np.all(fill(a, "mean") ==
              [[0.75, 200.,  10.],
               [2., 110.,  10.],
               [0., 120.,  11.],
               [0., 400.,  10.],
               [1., 207.5,   9.]])

assert np.all(fill(a, "min") ==
              [[0., 200.,  10.],
               [2., 110.,   9.],
               [0., 120.,  11.],
               [0., 400.,   9.],
               [1., 110.,   9.]])

assert np.all(fill(a, "max") ==
              [[2., 200.,  10.],
               [2., 110.,  11.],
               [0., 120.,  11.],
               [0., 400.,  11.],
               [1., 400.,   9.]])

Problem 9. Write a function to return a 2d array of given size with 1s on the border and 0s inside. 

Գրել ֆունկցիա, որը կվերադարձնի տրված չափանի երկչափ numpy array (քառակուսի մատրից), որտեղ եզրերում կլինեն 1-եր, իսկ ներսում՝ 0-ներ։  



In [ ]:
def zero_one(x):
  #your code here

In [ ]:
assert np.array_equal(zero_one(3), np.array([[1., 1., 1.],
                                            [1., 0., 1.],
                                            [1., 1., 1.]]))
assert np.array_equal(zero_one(4), np.array([[1., 1., 1., 1],
                                            [1., 0., 0., 1],
                                            [1., 0., 0., 1],
                                            [1., 1., 1., 1]]))

# Do not modify this cell
a = np.array([[-15, 1.5],
              [10, 7],
              [1, 35],
              [4, -5]])

b = np.array([[1, 16],
              [-1, 0],
              [-1, 50]])
p = 3

dist_mat(a, b, p)

In [ ]:
# Do not modify this cell
a = np.array([[-15, 1.5],
              [10, 7],
              [1, 35],
              [4, -5]])
b = np.array([[1, 16],
              [-1, 0],
              [-1, 50]])
p = 3
assert np.all(np.round(dist_mat(a, b, p)) ==
              [[19, 11, 19, 21],
               [14, 12, 35,  6],
               [49, 43, 15, 55]])

a = np.array([[-15, 1.5],
              [10, 7],
              [1, 35],
              [4, -5]])
b = np.array([[1, 16, 1],
              [-1, 0, 1]])
p = 3
assert dist_mat(a, b, p) == "DimensionError"

[[[ 1 16]]

 [[-1  0]]

 [[-1 50]]]


Problem 10. Այս խնդիրը լուծելու համար պետք է գրանցվել codesignal.com կայքում։ Այնուհետև պետք է անցնել [այս հղումով](https://app.codesignal.com/challenge/7BfPFxPyvvcJCzBuq) և լուծել խնդիրը։ Լուծումը ստուգելու համար պետք է ընտրեք "RUN SAMPLE TESTS" տարբերակը, իսկ հանձնելու համար՝ "SUBMIT" տարբերակը։ 